// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/clans": {
            "get": {
                "description": "Get List of Clan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clan"
                ],
                "summary": "Get All Clan",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Clan"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Clan",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clan"
                ],
                "summary": "Create Clan",
                "parameters": [
                    {
                        "description": "the body to create new clan",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ClanInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Clan"
                        }
                    }
                }
            }
        },
        "/clans/{id}": {
            "get": {
                "description": "Get one Clan by Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clan"
                ],
                "summary": "Get a Clan by Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clan Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Clan"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete one Clan by Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clan"
                ],
                "summary": "Delete a Clan by Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clan Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Clan by Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clan"
                ],
                "summary": "Update Clan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clan Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "the body to Update new clan",
                        "name": "Body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ClanInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Clan"
                        }
                    }
                }
            }
        },
        "/clans/{id}/shinobies": {
            "get": {
                "description": "Get all shinobies by Clan by Id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Clan"
                ],
                "summary": "Get shinobies by Clan by Id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Clan Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Shinobi"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.ClanInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Clan": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Shinobi": {
            "type": "object",
            "properties": {
                "clan_id": {
                    "description": "put the ClanID so it can GET Shinobi by Clan ID",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
